---
title: "Xaringan letter box effect in quarto"
format: xaringan-revealjs
auto-stretch: false
---

## Hello World

Install the **xaringan** package from [Github](https://github.com/yihui/xaringan):


```{r}
#| eval: false
#| echo: true
remotes::install_github("yihui/xaringan")
```

You are recommended to use the [RStudio IDE](https://www.rstudio.com/products/rstudio/), but you do not have to.

::: {.incremental}

- Create a new R Markdown document from the menu `File -> New File -> R Markdown -> From Template -> Ninja Presentation`;^[中文用户请看[这份教程](https://slides.yihui.org/xaringan/zh-CN.html)]

- Click the `Knit` button to compile it;

- or use the [RStudio Addin](https://rstudio.github.io/rstudioaddins/)^[See [#2](https://github.com/yihui/xaringan/issues/2) if you do not see the template or addin in RStudio.] "Infinite Moon Reader" to live preview the slides (every time you update and save the Rmd document, the slides will be automatically reloaded in RStudio Viewer.

## Hello Ninja

As a presentation ninja, you certainly should not be satisfied by the "Hello World" example. You need to understand more about two things:

1. The [remark.js](https://remarkjs.com) library;

1. The **xaringan** package;

Basically **xaringan** injected the chakra of R Markdown (minus Pandoc) into **remark.js**. The slides are rendered by remark.js in the web browser, and the Markdown source needed by remark.js is generated from R Markdown (**knitr**).

## remark.js

You can see an introduction of remark.js from [its homepage](https://remarkjs.com). You should read the [remark.js Wiki](https://github.com/gnab/remark/wiki) at least once to know how to

- create a new slide (Markdown syntax^[It is different with Pandoc's Markdown! It is limited but should be enough for presentation purposes. Come on... You do not need a slide for the Table of Contents! Well, the Markdown support in remark.js [may be improved](https://github.com/gnab/remark/issues/142) in the future.] and slide properties);

- format a slide (e.g. text alignment);

- configure the slideshow;

- and use the presentation (keyboard shortcuts).

It is important to be familiar with remark.js before you can understand the options in **xaringan**.
